name = "atlantic-backend-worker"
main = "src/index.js" # Pastikan path ini benar
compatibility_date = "2023-10-30"

# Binding untuk Durable Object
[durable_objects]
bindings = [
  # Nama 'DEPOSIT_STATUS' akan tersedia di `env.DEPOSIT_STATUS`.
  # Class 'DepositStatusNotifier' harus diekspor dari file `main`.
  { name = "DEPOSIT_STATUS", class_name = "DepositStatusNotifier" }
]

# Migrasi untuk mendaftarkan kelas Durable Object baru
[[migrations]]
tag = "v1"
new_classes = ["DepositStatusNotifier"]

# Variabel dan secrets
[vars]
BASE_URL = "https://atlantich2h.com"
CORS_ORIGIN = "https://pay.athars.me"

# [secrets]
# ATLANTIC_API_KEY
# ATLANTIC_USERNAME
